#!/usr/bin/make
#
# This makefile generated by LgiIde
# http://www.memecode.com/lgi.php
#

.SILENT :

CC = g++
Target = ihex
ifndef Build
	Build = Debug
endif
BuildDir = $(Build)Gcc

Flags = -fPIC -w -fno-inline -mno-cygwin
Defs = -DWIN32 -D_REENTRANT -D__MSVCRT__

ifeq ($(Build),Debug)
	Defs += -D_DEBUG
	Flags += -g
	Tag = d
else
	Flags += -s -Os
endif

# Libraries
Libs = \
			-LC:/Cygwin/lib/w32api \
			-L/lib/mingw \
			-limm32 \
			-lgdi32 \
			-Ld:/Home/matthew/Code/Lgi/$(BuildDir) \
			-llgi$(Tag)

# Includes
Inc = \
			-I../Lgi/include/common \
			-I../Lgi/include/win32 \
			-I./Code \
			-I/usr/include/mingw \
			-ID:/Home/matthew/CodeLib/libjpeg \
			-ID:/Home/matthew/CodeLib/libpng \
			-ID:/Home/matthew/CodeLib/zlib

# Dependencies
Depends =	iHex.o \
			MapLex.o \
			Png.o \
			SearchDlg.o \
			Visualiser.o \
			Gif.o \
			Lzw.o \
			GAbout.o \
			GDocApp.o \
			GDocView.o \
			GNew.o \
			GTextView3.o \
			LgiMain.o \
			GScripting.o \
			GScriptLibrary.o

# Target
# Executable target
$(Target) : ../Lgi/$(BuildDir)/liblgi$(Tag).dll outputfolder $(Depends)
	@echo Linking $(Target) [$(Gui)/$(Build)]...
	$(CC) -mno-cygwin -mwindows -Wl,--enable-auto-import -f -o \
		$(Target) $(addprefix $(BuildDir)/,$(Depends)) $(Libs)
	@echo Done.

../Lgi/$(BuildDir)/liblgi$(Tag).dll : FORCE
	export Build=$(Build); \
		export Gui=$(Gui); \
		$(MAKE) -C ../Lgi -f Makefile.mingw

FORCE :

# Create the output folder
outputfolder :
	-mkdir -p $(BuildDir) 2> /dev/null

# Clean out targets
clean :
	rm -f $(BuildDir)/*.o $(Target)..exe
	@echo Cleaned $(BuildDir)

iHex.o : ./Code/iHex.cpp ./Code/iHex.h \
	../Lgi/include/common/GToken.h \
	../Lgi/include/common/GAbout.h \
	./Code/resdefs.h \
	../Lgi/include/common/GCombo.h \
	../Lgi/include/common/GScrollBar.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

MapLex.o : ./Code/MapLex.cpp ../Lgi/include/common/Lgi.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

Png.o : ../Lgi/src/common/Gdc2/Filters/Png.cpp ../../CodeLib/libpng/png.h \
	../Lgi/include/common/Lgi.h \
	../Lgi/include/common/GFilterUtils.h \
	../Lgi/include/common/GVariant.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

SearchDlg.o : ./Code/SearchDlg.cpp ../Lgi/include/common/Lgi.h \
	./Code/iHex.h \
	./Code/resdefs.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

Visualiser.o : ./Code/Visualiser.cpp ../Lgi/include/common/Lgi.h \
	./Code/iHex.h \
	../Lgi/include/common/GList.h \
	../Lgi/include/common/GUtf8.h \
	./Code/resdefs.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

Gif.o : ../Lgi/src/common/Gdc2/Filters/Gif.cpp ../Lgi/include/common/Lgi.h \
	../Lgi/include/common/Lzw.h \
	../Lgi/include/common/GVariant.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

Lzw.o : ../Lgi/src/common/Gdc2/Filters/Lzw.cpp ../Lgi/include/common/Lgi.h \
	../Lgi/include/common/Lzw.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

GAbout.o : ../Lgi/src/common/Lgi/GAbout.cpp ../Lgi/include/common/Lgi.h \
	../Lgi/include/common/GAbout.h \
	../Lgi/include/common/GDocView.h \
	../Lgi/include/common/GBitmap.h \
	../Lgi/include/common/GButton.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

GDocApp.o : ../Lgi/src/common/Lgi/GDocApp.cpp ../Lgi/include/common/GDocApp.h \
	../Lgi/include/common/GToken.h \
	../Lgi/include/common/GOptionsFile.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

GDocView.o : ../Lgi/src/common/Text/GDocView.cpp ../Lgi/include/common/Lgi.h \
	../Lgi/include/common/GDocView.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

GNew.o : ../Lgi/src/common/General/GNew.cpp ../Lgi/include/common/GMem.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

GTextView3.o : ../Lgi/src/common/Text/GTextView3.cpp ../Lgi/include/common/Lgi.h \
	../Lgi/include/common/GTextView3.h \
	../Lgi/include/common/GInput.h \
	../Lgi/include/common/GScrollBar.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

LgiMain.o : ../Lgi/src/common/Lgi/LgiMain.cpp ../Lgi/include/common/Lgi.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

GScripting.o : ../Lgi/src/common/Coding/GScripting.cpp ../Lgi/include/common/Lgi.h \
	../Lgi/include/common/GScripting.h \
	../Lgi/include/common/GLexCpp.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

GScriptLibrary.o : ../Lgi/src/common/Coding/GScriptLibrary.cpp ../Lgi/include/common/Lgi.h \
	../Lgi/include/common/GScripting.h \
	../Lgi/include/common/GUtf8.h
	@echo $(<F)
	$(CC) $(Inc) $(Flags) $(Defs) -c $< -o $(BuildDir)/$(@F)

png.h : ../../CodeLib/zlib/zlib.h \
	../../CodeLib/libpng/pngconf.h

Lgi.h : ../Lgi/include/common/LgiInc.h \
	../Lgi/include/common/LgiMsgs.h \
	../Lgi/include/common/LgiDefs.h \
	../Lgi/include/common/GString.h \
	../Lgi/include/common/LgiClass.h \
	../Lgi/include/win32/LgiOsDefs.h \
	../Lgi/include/common/Progress.h \
	../Lgi/include/common/GFile.h \
	../Lgi/include/common/GMem.h \
	../Lgi/include/common/Gdc2.h \
	../Lgi/include/common/LgiRes.h \
	../Lgi/include/common/LgiClasses.h \
	../Lgi/include/common/LgiCommon.h

iHex.h : ../Lgi/include/common/Lgi.h \
	../Lgi/include/common/GAbout.h \
	../Lgi/include/common/GDocApp.h \
	../Lgi/include/common/GOptionsFile.h \
	../Lgi/include/common/GScripting.h \
	../Lgi/include/common/GTextView3.h

GFile.h : ../Lgi/include/win32/LgiOsDefs.h \
	../Lgi/include/common/GMem.h \
	../Lgi/include/common/GStream.h \
	../Lgi/include/common/GArray.h

LgiRes.h : ../Lgi/include/common/Res.h \
	../Lgi/include/common/GContainers.h

GContainers.h : ../Lgi/include/common/LgiInc.h \
	../Lgi/include/win32/LgiOsDefs.h \
	../Lgi/include/common/GStream.h

Res.h : ../Lgi/include/common/GXmlTree.h \
	../Lgi/include/common/GProperties.h

LgiCommon.h : ../Lgi/include/common/GArray.h \
	../Lgi/include/common/LgiClass.h

GXmlTree.h : ../Lgi/include/common/GHashTable.h

GProperties.h : ../Lgi/include/common/GContainers.h \
	../Lgi/include/common/LgiClass.h

GStream.h : ../Lgi/include/common/GDom.h

GToken.h : ../Lgi/include/common/GArray.h

GDocApp.h : ../Lgi/include/common/Lgi.h \
	../Lgi/include/common/GXml.h \
	../Lgi/include/common/GMru.h

GTextView3.h : ../Lgi/include/common/GDocView.h \
	../Lgi/include/common/GUndo.h

GVariant.h : ../Lgi/include/common/GDom.h \
	../Lgi/include/common/GDateTime.h \
	../Lgi/include/common/GContainers.h \
	../Lgi/include/common/GHashTable.h

GList.h : ../Lgi/include/common/GPopup.h \
	../Lgi/include/common/GArray.h

GXml.h : ../Lgi/include/common/GFile.h \
	../Lgi/include/common/GContainers.h

LgiClasses.h : ../Lgi/include/common/GSemaphore.h \
	../Lgi/include/common/GLibrary.h \
	../Lgi/include/win32/LgiOsClasses.h \
	../Lgi/include/common/GArray.h \
	../Lgi/include/common/LgiCommon.h \
	../Lgi/include/common/GXmlTree.h \
	../Lgi/include/common/GDragAndDrop.h \
	../Lgi/include/common/GMenu.h \
	../Lgi/include/common/LgiWidgets.h \
	../Lgi/include/common/Progress.h \
	../Lgi/include/common/GProgress.h \
	../Lgi/include/common/GFileSelect.h \
	../Lgi/include/common/GFindReplaceDlg.h \
	../Lgi/include/common/GToolBar.h \
	../Lgi/include/common/GThread.h \
	../Lgi/include/common/GClipBoard.h \
	../Lgi/include/common/GInput.h \
	../Lgi/include/common/GPrinter.h

GThread.h : ../Lgi/include/common/GSemaphore.h

GString.h : ../Lgi/include/common/LgiInc.h \
	../Lgi/include/common/LgiDefs.h

Progress.h : ../Lgi/include/common/GSemaphore.h

GMem.h : ../Lgi/include/common/LgiDefs.h \
	../Lgi/include/common/LgiInc.h

GArray.h : ../Lgi/include/common/LgiDefs.h \
	../Lgi/include/common/GMem.h

LgiOsDefs.h : ../Lgi/include/common/LgiInc.h \
	../Lgi/include/common/LgiDefs.h \
	../Lgi/include/common/LgiClass.h

GLexCpp.h : ../Lgi/include/common/LgiInc.h \
	../Lgi/include/common/LgiDefs.h \
	../Lgi/include/common/GString.h \
	../Lgi/include/win32/LgiOsDefs.h

GOptionsFile.h : ../Lgi/include/common/GVariant.h \
	../Lgi/include/common/GXmlTree.h \
	../Lgi/include/common/GSemaphore.h

GDom.h : ../Lgi/include/common/LgiInterfaces.h \
	../Lgi/include/common/GArray.h

LgiInterfaces.h : ../Lgi/include/common/GArray.h

zlib.h : ../../CodeLib/zlib/zconf.h

GAbout.h : ../Lgi/include/common/GDocView.h

LgiOsClasses.h : ../Lgi/include/common/GContainers.h

GMenu.h : ../Lgi/include/common/GMenuImpl.h \
	../Lgi/include/common/GXmlTree.h \
	../Lgi/include/common/Res.h

GMenuImpl.h : ../Lgi/include/common/GPopup.h

GHashTable.h : ../Lgi/include/common/GArray.h \
	../Lgi/include/common/GString.h

LgiClass.h : ../Lgi/include/common/LgiInc.h

Gdc2.h : ../Lgi/include/common/LgiDefs.h \
	../Lgi/include/common/LgiClass.h \
	../Lgi/include/win32/LgiOsDefs.h \
	../Lgi/include/common/Progress.h \
	../Lgi/include/common/GFile.h \
	../Lgi/include/common/GMem.h \
	../Lgi/include/win32/Core.h \
	../Lgi/include/common/GContainers.h \
	../Lgi/include/common/GLibrary.h \
	../Lgi/include/common/GRect.h \
	../Lgi/include/common/GFont.h \
	../Lgi/include/common/GFilter.h

GFont.h : ../Lgi/include/common/GRect.h \
	../Lgi/include/common/GProperties.h \
	../Lgi/include/win32/LgiOsClasses.h \
	../Lgi/include/common/GLibrary.h \
	../Lgi/include/common/GFilterUtils.h

GFilter.h : ../Lgi/include/common/GContainers.h \
	../Lgi/include/common/GProperties.h

GScripting.h : ../Lgi/include/common/GVariant.h

GDragAndDrop.h : ../Lgi/include/common/GVariant.h \
	../Lgi/include/win32/GCom.h

VPATH=%.cpp \
	$(BuildDir)

